apiVersion: v1
kind: Secret
metadata:
  name: instana-agent-secret
  namespace: NAMESPACE  # <-- zamień na swój namespace, np. workshop-user01
type: Opaque
stringData:
  key: INSTANA_AGENT_KEY  # <-- wklej klucz agenta od prowadzącego
